---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: default
spec:
  interval: 10m
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: default
spec:
  releaseName: cilium
  targetNamespace: kube-system
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: GitRepository
        name: homelab
      interval: 5m
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
