---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-release
  namespace: default
spec:
  interval: 30m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: default
spec:
  releaseName: rook-ceph-operator
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      #      version: "1.17.6"
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 5m
  interval: 10m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: default
spec:
  dependsOn:
    - name: rook-ceph-operator
  releaseName: rook-ceph-cluster
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph-cluster
      version: "1.17.7"
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 5m
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operatorNamespace=rook-ceph