# Default values for cilium.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cilium:
  ipam.mode: kubernetes
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 7445
  securityContext:
    capabilities:
      ciliumAgent: [ "CHOWN","KILL","NET_ADMIN","NET_RAW","IPC_LOCK","SYS_ADMIN","SYS_RESOURCE","DAC_OVERRIDE","FOWNER","SETGID","SETUID" ]
      cleanCiliumState: [ "NET_ADMIN","SYS_ADMIN","SYS_RESOURCE" ]
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  gatewayAPI:
    enabled: true
    enableAlpn: true
    enableAppProtocol: true
